# Generated by Django 4.2.21 on 2025-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role_clientadminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('master_admin', 'Master Admin'), ('client_admin', 'Client Admin'), ('end_user', 'End User'), ('supplier', 'Supplier')], max_length=20),
        ),
    ]
