# Generated by Django 4.2.21 on 2025-06-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientadminprofile_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduserprofile',
            name='client_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_users', to='core.clientadminprofile'),
        ),
    ]
