# Generated by Django 4.2.21 on 2025-06-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enduserprofile_client_admin'),
    ]

    operations = [
    ]
