# Generated by Django 4.2.21 on 2025-06-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enduserprofile_email_enduserprofile_password_and_more'),
    ]

    operations = [
    ]
