# Generated by Django 4.2.21 on 2025-06-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_set_default_enduser_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduserprofile',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='enduserprofile',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
