# Generated by Django 4.2.21 on 2025-06-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_customuser_client_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduserprofile',
            old_name='organization_name',
            new_name='organization',
        ),
    ]
