# Generated by Django 4.2.21 on 2025-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_organization_name_enduserprofile_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(max_length=50, unique=True)),
                ('commodity_name', models.CharField(max_length=225)),
            ],
        ),
    ]
