# Generated by Django 4.2.21 on 2025-06-10 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_commodity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQImportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_pr_number', models.CharField(max_length=100)),
                ('client_requestor_name', models.CharField(max_length=100)),
                ('client_requestor_id', models.CharField(max_length=100)),
                ('client_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('shipping_address', models.TextField(max_length=100)),
                ('Currency', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('need_by_date', models.DateField()),
                ('supplier_part_number', models.CharField(max_length=100)),
                ('drawing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('commodity_code', models.CharField(max_length=50)),
                ('uom', models.CharField(max_length=50)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier_name', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturer_part_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
