# Generated by Django 4.2.21 on 2025-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rfqimportdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_pr_number', models.CharField(max_length=100)),
                ('client_requestor_name', models.CharField(max_length=100)),
                ('client_requestor_id', models.CharField(max_length=100)),
                ('client_item_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('shipping_address', models.TextField()),
                ('currency', models.CharField(max_length=20)),
                ('rfq_type', models.CharField(max_length=50)),
                ('assignee', models.CharField(max_length=100)),
                ('serial_number', models.IntegerField()),
                ('description', models.TextField()),
                ('need_by_date', models.DateField()),
                ('supplier_part_number', models.CharField(max_length=100)),
                ('commodity_code', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacturer_part_number', models.CharField(max_length=100)),
                ('benchmark_price', models.FloatField()),
                ('rfq_status', models.CharField(max_length=100)),
                ('supplier_code', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('lead_time', models.CharField(max_length=50)),
                ('inco_terms', models.CharField(max_length=50)),
                ('payment_terms', models.CharField(max_length=100)),
                ('freight', models.CharField(max_length=50)),
                ('alternative_part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('chat_box_comments', models.TextField(blank=True, null=True)),
                ('rfq_received_date', models.DateField(blank=True, null=True)),
                ('rfq_opened_date', models.DateField(blank=True, null=True)),
                ('rfq_closed_date', models.DateField(blank=True, null=True)),
                ('rfq_award_date', models.DateField(blank=True, null=True)),
                ('awarded_price', models.FloatField(blank=True, null=True)),
                ('rfq_archived_date', models.DateField(blank=True, null=True)),
                ('rfq_cancelled_date', models.DateField(blank=True, null=True)),
                ('reason_for_cancel', models.TextField(blank=True, null=True)),
                ('reason_for_archive', models.TextField(blank=True, null=True)),
                ('bidding_declined', models.CharField(blank=True, max_length=50, null=True)),
                ('rfq_reopened_date_1', models.DateField(blank=True, null=True)),
                ('rfq_closed_date_1', models.DateField(blank=True, null=True)),
                ('rfq_reopened_date_2', models.DateField(blank=True, null=True)),
                ('rfq_closed_date_2', models.DateField(blank=True, null=True)),
                ('rfq_reopened_date_3', models.DateField(blank=True, null=True)),
                ('rfq_closed_date_3', models.DateField(blank=True, null=True)),
                ('savings', models.FloatField(blank=True, null=True)),
                ('savings_percent', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
