# Generated by Django 4.2.21 on 2025-06-16 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rfqmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmanagement',
            name='rfq_import',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_management', to='core.rfqimportdata'),
        ),
        migrations.AlterField(
            model_name='enduserprofile',
            name='password',
            field=models.CharField(help_text='Hashed password from CustomUser', max_length=255),
        ),
    ]
