# Generated by Django 4.2.21 on 2025-06-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rfqmanagement_rfq_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqmanagement',
            name='selected_suppliers',
            field=models.ManyToManyField(blank=True, related_name='rfqs_assigned', to='core.supplier'),
        ),
        migrations.AlterField(
            model_name='rfqmanagement',
            name='rfq_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfq_management', to='core.rfqimportdata'),
        ),
    ]
