# Generated by Django 4.2.21 on 2025-06-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rfqmanagement_selected_suppliers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfqmanagement',
            name='rfq_status',
        ),
        migrations.AddField(
            model_name='rfqmanagement',
            name='awarded_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_rfqs', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='rfqmanagement',
            name='status',
            field=models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='opened', max_length=20),
        ),
    ]
