# Generated by Django 4.2.21 on 2025-06-21 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_rfqmanagement_rfq_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('opened', 'Opened'), ('closed', 'Closed'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('supplier_responses', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rfq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.rfqmanagement')),
            ],
        ),
    ]
