# Generated by Django 4.2.21 on 2025-06-27 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_supplierresponsetoken_supplierresponse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierresponse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='supplierresponsetoken',
            name='rfq_management',
        ),
        migrations.AddField(
            model_name='supplierresponse',
            name='rfq_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rfqimportdata'),
        ),
        migrations.AddField(
            model_name='supplierresponsetoken',
            name='rfq_import',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.rfqimportdata'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='supplierresponse',
            unique_together={('rfq_import', 'supplier')},
        ),
        migrations.RemoveField(
            model_name='supplierresponse',
            name='rfq_management',
        ),
    ]
