# Generated by Django 4.2.21 on 2025-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_supplierresponse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='commodities',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='core.commodity'),
        ),
    ]
